#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : mentiphy  # The title of the book. Will be placed in the left navbar.
author                      : Emil Sarling & Emma Söderström  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : img/lo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kladdy/mentiphy  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Disable GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false

# Configure sphinx to use Swedish strings, such as search_bar_text
# Do "jupyter-book config sphinx mentiphy" to get the options given this _config.yml
sphinx:
  config: 
    html_theme: "sphinx_book_theme"
    html_theme_options:
      search_bar_text: "Sök på Mentiphy..."
      # launch_buttons:
      #   notebook_interface: "classic"
      #   binderhub_url: ""
      #   jupyterhub_url: ""
      #   thebe: false
      #   colab_url: ""
      # path_to_docs: ""
      # repository_url: ""
      # repository_branch: "master"
      extra_footer: |
        <div>
          <div>Vi finns på <a href='https://youtube.com/@mentiphy1'>YouTube</a>. <br>Kontakta oss på <a href='mailto:info@mentiphy.se'>info@mentiphy.se</a>. <br>Hemsidan drivs av <a href='https://consulting.stjarnholm.com'>Stjärnholm Consulting</a>.</div>
          <!-- Cookie Consent by PrivacyPolicies.com https://www.PrivacyPolicies.com -->
          <script type="text/javascript" src="https://www.privacypolicies.com/public/cookie-consent/4.1.0/cookie-consent.js" charset="UTF-8"></script>
          <script type="text/javascript" charset="UTF-8">
          document.addEventListener('DOMContentLoaded', function () {
          cookieconsent.run({"notice_banner_type":"interstitial","consent_type":"express","palette":"light","language":"sv","page_load_consent_levels":["strictly-necessary"],"notice_banner_reject_button_hide":false,"preferences_center_close_button_hide":false,"page_refresh_confirmation_buttons":false,"website_name":"Mentiphy","website_privacy_policy_url":"https://clarity.microsoft.com/terms"});
          });
          </script>

          <!-- Microsoft Clarity -->
          <script type="text/plain" cookie-consent="tracking">
              (function(c,l,a,r,i,t,y){
                  c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                  t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                  y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "h0v59y70qe");
          </script>
          <!-- end of Microsoft Clarity-->

          <noscript>Cookie Consent by <a href="https://www.privacypolicies.com/" rel="noopener">Privacy Policies website</a></noscript>
          <!-- End Cookie Consent by PrivacyPolicies.com https://www.PrivacyPolicies.com -->
        </div>
      home_page_in_toc: true
      # announcement: ""
      # analytics:
      #   google_analytics_id: ""
      # use_repository_button: false
    language: sv

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist